# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" =
    { device = "/dev/sda1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "noatime" "nodev" "noexec" "nosuid"];
    };
    
  fileSystems."/" =
    { device = "/dev/vg_nixos/lv_root";
      fsType = "ext4";
      options = ["defaults" "noatime"];
    };

  fileSystems."/home" =
    { device = "/dev/vg_nixos/lv_home";
      fsType = "ext4";
      options = ["defaults" "noatime" "nodev" "nosuid"];
    };
    
  fileSystems."/mnt/jellyfin" =
    { device = "/dev/vg_nixos/lv_syncthing";
      fsType = "ext4";
      options = ["defaults" "noatime" "rw"  "nodev" "noexec" "nosuid"];
    };
    
  fileSystems."/tmp" =
    { device = "/dev/vg_nixos/lv_tmp";
      fsType = "ext4";
      options = ["defaults" "noatime" "rw" "nodev" "noexec" "nosuid" "mode=1777"];
    };

  fileSystems."/var" =
    { device = "/dev/vg_nixos/lv_var";
      fsType = "ext4";
      options = ["defaults" "noatime" "rw"  "nodev" "noexec" "nosuid"];
    };

  
    
  

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwp0s20u6i4.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
